name: 'trivy-misconf-scan'
description: 'Misconfiguration Scanner with Trivy'
author: 'mrtc0'
inputs:
  policy-repository:
    description: 'Policy repository'
    required: false
    default: ''
  policy-directory:
    description: 'Policy directory'
    required: false
    default: ''
  namespaces:
    description: 'Policy namespaces'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - '-a ${{ inputs.policy-repository }}'
    - '-b ${{ inputs.policy-directory }}'
    - '-c ${{ inputs.namespaces }}'
